// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwp2eTEWhFBF99seeiSkmQbHMYO4sIHyM',
    appId: '1:709111486362:web:8e3068e0ec4946aa02cc23',
    messagingSenderId: '709111486362',
    projectId: 'partypal-16857',
    authDomain: 'partypal-16857.firebaseapp.com',
    storageBucket: 'partypal-16857.appspot.com',
    measurementId: 'G-1Y173Y1BRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNsQQRMyHCWT_blOtoHdMkxk0InkBd004',
    appId: '1:709111486362:android:a659f46b57d2a8b902cc23',
    messagingSenderId: '709111486362',
    projectId: 'partypal-16857',
    storageBucket: 'partypal-16857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnSxbZdh6TROb-Nb6n3YKKnwF4PZzSXgA',
    appId: '1:709111486362:ios:efd34de915291b3302cc23',
    messagingSenderId: '709111486362',
    projectId: 'partypal-16857',
    storageBucket: 'partypal-16857.appspot.com',
    androidClientId: '709111486362-3jmd5mcjcl1vtgsvvele0dll513s64f3.apps.googleusercontent.com',
    iosClientId: '709111486362-hdurccd4phc619tev7ono169gvqh4icq.apps.googleusercontent.com',
    iosBundleId: 'com.example.partypal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnSxbZdh6TROb-Nb6n3YKKnwF4PZzSXgA',
    appId: '1:709111486362:ios:efd34de915291b3302cc23',
    messagingSenderId: '709111486362',
    projectId: 'partypal-16857',
    storageBucket: 'partypal-16857.appspot.com',
    androidClientId: '709111486362-3jmd5mcjcl1vtgsvvele0dll513s64f3.apps.googleusercontent.com',
    iosClientId: '709111486362-hdurccd4phc619tev7ono169gvqh4icq.apps.googleusercontent.com',
    iosBundleId: 'com.example.partypal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwp2eTEWhFBF99seeiSkmQbHMYO4sIHyM',
    appId: '1:709111486362:web:36efd90cd08ad68d02cc23',
    messagingSenderId: '709111486362',
    projectId: 'partypal-16857',
    authDomain: 'partypal-16857.firebaseapp.com',
    storageBucket: 'partypal-16857.appspot.com',
    measurementId: 'G-6EZ17PMX2J',
  );
}
